/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Classes.Abstratas;

public class App {
    public static void main(String[] args) {
      Sofa meuSofa = new Sofa("vermelho", "couro");
      Mesa minhamesa = new Mesa("azul", "metal");
      meuSofa.montar();
      meuSofa.desmontar();
      minhamesa.desmontar();
      minhamesa.montar();
    }
}
